In [8]:
import numpy as np

array = np.random.rand(3, 3)

print(array)
diff = array[:, np.newaxis, :] - array[np.newaxis, :, :]
print(diff)
print("!")
print(np.sum(diff**2,axis=2))
euclidean_distances = np.sqrt(np.sum(diff**2, axis=2))

print("Array:\n", array)
print("\nPairwise Euclidean distances:\n", euclidean_distances)


[[0.57173661 0.19899757 0.27731463]
 [0.90136193 0.11594243 0.41120118]
 [0.18650969 0.71278081 0.52616589]]
[[[ 0.          0.          0.        ]
  [-0.32962531  0.08305514 -0.13388655]
  [ 0.38522693 -0.51378324 -0.24885126]]

 [[ 0.32962531 -0.08305514  0.13388655]
  [ 0.          0.          0.        ]
  [ 0.71485224 -0.59683838 -0.11496471]]

 [[-0.38522693  0.51378324  0.24885126]
  [-0.71485224  0.59683838  0.11496471]
  [ 0.          0.          0.        ]]]
!
[[0.         0.13347661 0.47429995]
 [0.13347661 0.         0.88044666]
 [0.47429995 0.88044666 0.        ]]
Array:
 [[0.57173661 0.19899757 0.27731463]
 [0.90136193 0.11594243 0.41120118]
 [0.18650969 0.71278081 0.52616589]]

Pairwise Euclidean distances:
 [[0.         0.36534451 0.68869438]
 [0.36534451 0.         0.93832119]
 [0.68869438 0.93832119 0.        ]]
