. Write a NumPy program to calculate the Frobenius norm and the condition number of a given array.


In [1]:
import numpy as np

a = np.arange(1, 10).reshape((3, 3))

print("Original array:")
print(a)

print("Frobenius norm and the condition number:")
print(np.linalg.norm(a, 'fro'))  
print(np.linalg.cond(a, 'fro'))

Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Frobenius norm and the condition number:
16.881943016134134
inf
