40. Write a NumPy program to compute xy, element-wise where x, y are two given arrays.

Sample output:
Array1:
[[1 2]
[3 4]]

Array1:
[[1 2]
[1 2]]

Result- x^y:
[[ 1 4]
[ 3 16]]

In [1]:
import numpy as np


num1=np.array([[1,2],[3,4]])
num2=([[1,2],[1,2]])
r1=np.power(num1,num2)
print(r1)

[[ 1  4]
 [ 3 16]]
