NumPy Array Copy vs View


The Difference Between Copy and View


The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

In [5]:
pip install numpy

     ---------------------------------------- 12.9/12.9 MB 3.8 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


ERROR: Could not install packages due to an OSError: [WinError 2] The system cannot find the file specified: 'c:\\Python310\\Scripts\\f2py.exe' -> 'c:\\Python310\\Scripts\\f2py.exe.deleteme'


[notice] A new release of pip available: 22.2.2 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [6]:
import numpy as np

In [8]:
num1=np.array([1,2,3,4,5])
num2=num1.copy()
num2[0]=23
print(num1)
print(num2)

[1 2 3 4 5]
[23  2  3  4  5]


VIEW

In [9]:
num1=np.array([1,2,3,4,5])
num2=num1.view()
num2[0]=23
print(num1)
print(num2)

[23  2  3  4  5]
[23  2  3  4  5]


In [12]:
## array.base return the none if the element doesnt own the data

num1=np.array([1,2,3,4,5])
num2=num1.copy() ## .copy has its own data so if we make a chnage than it cannot reflect on original array
num3=num1.view() ## .view has been work as a address reference to teh array so the changes made up on the array directly refers on the array
print(num3.base)
print(num2.base)  

[1 2 3 4 5]
None


Get the Shape of an Array


In [14]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr)
print(arr.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [15]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In [16]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [17]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [ ]:
##Try converting 1D array with 8 elements to a 2D array with 3 elements in each dimension (will raise an error):

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(3, 3)

print(newarr)

ValueError: cannot reshape array of size 8 into shape (3,3)

In [21]:
##Check if the returned array is a copy or a view: returns the view

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(arr.reshape(2, 4).base)

[1 2 3 4 5 6 7 8]


In [23]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8,9,10,11,12])

newarr = arr.reshape(2, 2, 3)

print(newarr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [24]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Flattening the arrays

Flattening array means converting a multidimensional array into a 1D array.

We can use reshape(-1) to do this.

In [25]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


In [26]:
import numpy as np

arr = np.array([1, 2, 3])
arr1 = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)
for x in arr1:
  print(x)

1
2
3
[1 2 3]
[4 5 6]


In [27]:
for x in arr1:
    print(x[0])

1
4


In [28]:
for x in arr1:
    for y in x:
        print(y)

1
2
3
4
5
6


In [29]:
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [30]:
for x in arr3:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [31]:
for x in np.nditer(arr1):
    print(x)

1
2
3
4
5
6


In [32]:
for x in np.nditer(arr1[:,::2]):
    print(x)

1
3
4
6


In [33]:
for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [34]:
for idx,x in np.ndenumerate(arr1):
    print(idx,x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6


Joining NumPy Arrays


Joining means putting contents of two or more arrays in a single array.

We pass a sequence of arrays that we want to join to the concatenate() function, along with the axis. If axis is not explicitly passed, it is taken as 0.



In [35]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [51]:
## when we use the axis=1  the contextual concatination of element can be done in the vertical manner
## when we use the axis=0  the contextual concatination of element can be done in the horizontal manner

arr1 = np.array([[1, 2],[4, 3]])

arr2 = np.array([[4, 5],[7, 6]])
arr = np.concatenate((arr1, arr2),axis=0)


In [52]:
print(arr)

[[1 2]
 [4 3]
 [4 5]
 [7 6]]


In [48]:
print(arr.ndim)

2


Joining Arrays Using Stack Functions


Stacking is same as concatenation, the only difference is that stacking is done along a new axis.

We can concatenate two 1-D arrays along the second axis which would result in putting them one over the other, ie. stacking.

We pass a sequence of arrays that we want to join to the stack() method along with the axis. If axis is not explicitly passed it is taken as 0.

In [49]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr=np.stack((arr1,arr2),axis=1)

In [50]:
print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [53]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr=np.stack((arr1,arr2),axis=0)

In [54]:
print(arr)

[[1 2 3]
 [4 5 6]]


In [55]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr=np.hstack((arr1,arr2))

In [56]:
print(arr)

[1 2 3 4 5 6]


In [58]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr=np.vstack((arr1,arr2))
print(arr)
print(arr.ndim)

[[1 2 3]
 [4 5 6]]
2


In [59]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr=np.dstack((arr1,arr2))
print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


In [60]:
arr = np.array([1, 2, 3, 4, 5, 6])
arr1=np.array_split(arr,3)

In [61]:
print(arr1)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [62]:
arr = np.array([1, 2, 3, 4, 5, 6])
arr1=np.array_split(arr,4)
print(arr1)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [63]:
print(arr1[0])

[1 2]


In [68]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

arr1=np.array_split(arr,2)
print(arr1)

[array([[1, 2],
       [3, 4],
       [5, 6]]), array([[ 7,  8],
       [ 9, 10],
       [11, 12]])]


In [72]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
print(arr)
arr1=np.array_split(arr,3,axis=1)
print(arr1)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [75]:
newarr=np.vsplit(arr,3)

In [76]:
print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]
