20. Write a NumPy program that Multiplies each column of a 2D array x of shape (7, 3)
 by a 1D array y of shape (7,) using broadcasting.


In [7]:
import numpy as np
from numpy import random

num1=random.randint(1,10,size=(7,3))
print(num1)
print()
num2=random.randint(1,10,size=(7,))
print(num2)
print(num2[:,np.newaxis])
print()
num3 = num1 * num2[:, np.newaxis]
print("The Multiplied Array:::")
print(num3)


[[5 1 4]
 [1 2 8]
 [4 8 7]
 [3 1 2]
 [8 2 5]
 [4 9 2]
 [6 4 6]]

[2 5 5 7 3 6 4]
[[2]
 [5]
 [5]
 [7]
 [3]
 [6]
 [4]]

The Multiplied Array:::
[[10  2  8]
 [ 5 10 40]
 [20 40 35]
 [21  7 14]
 [24  6 15]
 [24 54 12]
 [24 16 24]]


Write a  NumPy program to create a 3D array x of shape (3, 1, 5) and a 2D array y of shape (3, 5). Add x and y using broadcasting.



In [10]:
import numpy as np

# Create a 3D array x of shape (3, 1, 5)
x = np.array([[[1, 2, 3, 4, 5]],
              [[6, 7, 8, 9, 10]],
              [[11, 12, 13, 14, 15]]])

# Create a 2D array y of shape (3, 5)
y = np.array([[10, 20, 30, 40, 50],
              [15, 25, 35, 45, 55],
              [20, 30, 40, 50, 60]])
print(y[:,np.newaxis,:])
res=x+y[:,np.newaxis,:]

[[[10 20 30 40 50]]

 [[15 25 35 45 55]]

 [[20 30 40 50 60]]]


In [9]:
print(res)

[[[11 22 33 44 55]]

 [[21 32 43 54 65]]

 [[31 42 53 64 75]]]
