41. Write a NumPy program to compute an 

element-wise indication of the sign for all 
elements in a given array.

Sample output:

Original array;
[ 1 3 5 0 -1 -7 0 5]

Element-wise indication of the sign for all elements of the said array:
[ 1 1 1 0 -1 -1 0 1]

In [1]:
import numpy as np

x = np.array([1, 3, 5, 0, -1, -7, 0, 5])

print("Original array;")
print(x)

r1 = np.sign(x)

r2 = np.copy(x)
r2[r2 > 0] = 1  
r2[r2 < 0] = -1  

assert np.array_equal(r1, r2)

print("Element-wise indication of the sign for all elements of the said array:")
print(r1)


Original array;
[ 1  3  5  0 -1 -7  0  5]
[ 1  3  5  0 -1 -7  0  5]
Element-wise indication of the sign for all elements of the said array:
[ 1  1  1  0 -1 -1  0  1]
