numpy Io Operations

In [5]:
import numpy as np
num1=np.array([[1,2,3],[4,5,6]])
file_name="demo.csv"

np.savetxt(file_name,num1,fmt="%d",delimiter=";")
print("text has been saved")
load_txt=np.loadtxt(file_name,delimiter=";")
print(load_txt)

text has been saved
[[1. 2. 3.]
 [4. 5. 6.]]


20. Write a NumPy program to append a NumPy array to a Python list and print the result.


In [9]:
import numpy as np
num1=np.array([1,2,3,4,5,6,7])
file_name="temp.csv"
list1=[1,2,3,4,5,6]
num1=num1.tolist()
list1.extend(num1)

np.savetxt(file_name,list1,fmt="%d",delimiter=",")

print("data has been saved")

data=np.loadtxt(file_name,delimiter=",")
print(data[0:3])

data has been saved
[1. 2. 3.]


In [ ]:
""