In [2]:
pip install numpy

                                              0.0/12.9 MB ? eta -:--:--
                                              0.1/12.9 MB 1.3 MB/s eta 0:00:10
                                              0.2/12.9 MB 2.1 MB/s eta 0:00:07
                                              0.3/12.9 MB 2.5 MB/s eta 0:00:06
     ---                                      1.0/12.9 MB 5.3 MB/s eta 0:00:03
     ------                                   2.1/12.9 MB 8.8 MB/s eta 0:00:02
     -------                                  2.3/12.9 MB 9.3 MB/s eta 0:00:02
     -------                                  2.3/12.9 MB 9.3 MB/s eta 0:00:02
     --------                                 2.7/12.9 MB 7.6 MB/s eta 0:00:02
     -----------                              3.7/12.9 MB 9.4 MB/s eta 0:00:01
     -----------                              3.7/12.9 MB 9.4 MB/s eta 0:00:01
     -----------                              3.7/12.9 MB 7.1 MB/s eta 0:00:02
     --------------                           4.7/12.9 MB 8


[notice] A new release of pip is available: 23.1.2 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
import numpy as np

In [4]:
num1=np.array([1,2,3,4,5])
print(num1)
print(type(num1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [5]:
num2=np.array((2,4,6,8,7,6,5,2,1))

In [6]:
print(num2)

[2 4 6 8 7 6 5 2 1]


In [7]:
print(np.__version__)

2.2.1


In [10]:
#creates a 0 dimention array
arr=np.array(42)

In [11]:
arr

array(42)

In [16]:
#create a one dimention array

arr1=np.array([1,2,3,4,5])
print(arr1)

[1 2 3 4 5]


In [18]:
##2-d matrix

num1=np.array([[1,2,3],[4,5,6]])
print(num1)


[[1 2 3]
 [4 5 6]]


In [22]:
num2=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

print(num2[0,1])


[4 5 6]


In [24]:
print(num1.ndim)
print(num2.ndim)

2
3


In [28]:
mutli=np.array([1,2,3,4,5],ndmin=5)

In [29]:
print(mutli)

[[[[[1 2 3 4 5]]]]]


In [30]:
print(mutli.ndim)

5


In [33]:
# Accessing the elements in the 2D Array
# num[row no,col no]

print(num1)
print(num1[0,1])

[[1 2 3]
 [4 5 6]]
2


In [34]:
# Access the element of the 3-D Array

print(num2)
print(num2[0,1,2])

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
6


In [38]:
## Access the element using the negetive index

print(num1)
print(num1[-1,2])

[[1 2 3]
 [4 5 6]]
6


In [40]:
#Array Slicing for num[i,j] for the range is from the i to j-1
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [41]:
#Array Slicing for num[i:] for the range is from the i to j-1
# This means the range is from i to the end

print(arr[2:])

[3 4 5 6 7]


In [42]:
## nums[:i] Slice elements from the beginning to index i (not included):

print(arr[:5])

[1 2 3 4 5]


In [43]:
print(arr[-3:-1])

[5 6]


In [44]:
print(arr[1:5:2])

[2 4]


In [45]:
print(arr[::2])

[1 3 5 7]


In [46]:
##Slicing 2-D Arrays


In [47]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


In [49]:
#returns the 2nd value from the two arrays

print(arr[0:2,2])

[3 8]


In [50]:
print(arr[0:2, 1:4])


[[2 3 4]
 [7 8 9]]


Data Types in Python

By default Python have these data types:

strings - used to represent text data, the text is given under quote marks. e.g. "ABCD"

integer - used to represent integer numbers. e.g. -1, -2, -3

float - used to represent real numbers. e.g. 1.2, 42.42

boolean - used to represent True or False.

complex - used to represent complex numbers. e.g. 1.0 + 2.0j, 1.5 + 2.5j

In [51]:
print(arr.dtype)

int64


In [54]:
nums=np.array(["banana2","ap2ple","guaua"])

In [55]:
print(nums.dtype)

<U7



Creating Arrays With a Defined Data Type

We use the array() function to create arrays, this function can take an optional argument: dtype that allows us to define the expected data type of the array elements:



In [57]:
temp=np.array([1,2,3,4,5],dtype=float)
print(temp)

[1. 2. 3. 4. 5.]


What if a Value Can Not Be Converted?


In [58]:
arr = np.array(['a', '2', '3'], dtype='i')


ValueError: invalid literal for int() with base 10: 'a'

In [63]:
##  Type Conversion

arr=np.array([1.1,1.2,1.3])
arr1=arr.astype(int)
print(arr1)
print(arr1.dtype)

[1 1 1]
int64


In [65]:
#number which is non zero it will return True

arr2=arr.astype(bool)
print(arr2)
print(arr2.dtype)

[ True  True  True]
bool
