Searching Arrays

You can search an array for a certain value, and return the indexes that get a match.

To search an array, use the where() method.

In [7]:
import numpy as np
arr = np.array([1, 2, 3, 4, 4, 4])
x=np.where(arr==4)
print(x[0][0])

3


In [8]:
x=np.where(arr%2==0)
print(x)

(array([1, 3, 5, 6]),)


In [11]:
x=np.searchsorted(arr,3)

In [12]:
x

np.int64(2)

In [17]:
## uses the searchsorted function that finds the vakue that can be inserted at the existing index
## in below example the value 2 and 4 can be inserted at index 1 means after 1 and before 5 so it returns the index 1
## 6 can be inserted at index 2 between 5 and 7

import numpy as np

arr = np.array([1,5,7,9])

x = np.searchsorted(arr, [2, 4, 6])

print(x)

[1 1 2]


Sorting Arrays

Sorting means putting elements in an ordered sequence.

Ordered sequence is any sequence that has an order corresponding to elements, like numeric or alphabetical, ascending or descending.

The NumPy ndarray object has a function called sort(), that will sort a specified array.

In [18]:
import numpy as np

arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


In [19]:
arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


In [20]:
arr = np.array([True, False, True])

print(np.sort(arr))

[False  True  True]


Sorting a 2-D Array


In [26]:
arr = np.array([[9,3, 2, 4], [6,5, 0, 1]])
print(np.sort(arr))

[[2 3 4 9]
 [0 1 5 6]]


NumPy Filter Array


Filtering Arrays
Getting some elements out of an existing array and creating a new array out of them is called filtering.

In NumPy, you filter an array using a boolean index list.

A boolean index list is a list of booleans corresponding to indexes in the array.

If the value at an index is True that element is contained in the filtered array, if the value at that index is False that element is excluded from the filtered array.

In [27]:
import numpy as np

arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)

[41 43]


In [28]:
'''Example
Create a filter array that will return only values higher than 42:'''


import numpy as np
arr1=np.array((1,2,3,4))
list=[]
for x in arr1:
    if x%2==0:
        list.append(True)
    else:
        list.append(False)
newarr=arr1[list]
print(newarr)

[2 4]


In [29]:
## The simpler solution is::

import numpy as np
arr1=np.array((1,2,3,4,5,6))

condi=  arr1%2==0

newarr=arr1[condi]

In [30]:
print(newarr)

[2 4 6]
