20. Write a NumPy program that creates a large NumPy array and write a function to reverse its elements using a for loop. Optimize it using NumPy's slicing operations.


In [ ]:
#reverse the array with simple methods

In [13]:
import numpy as np

from numpy import random

num1=np.arange(0,1001)

In [9]:
print(num1)

[   0    1    2 ...  998  999 1000]


In [10]:
def reverse_arr(arr):
    rev_like=np.empty_like(arr)
    n=len(arr)
    for i in range(n):
        rev_like[i]=arr[n-i-1]
    return rev_like

num2=reverse_arr(num1)
print(num2)

[1000  999  998 ...    2    1    0]


In [11]:
##using the numpy slicing:'


In [14]:
def reverse_array(arr):
    return arr[::-1]
num2=reverse_arr(num1)
print(num2)

[1000  999  998 ...    2    1    0]
