3. Strides:

The stride indicates the number of bytes to move in each dimension when accessing the array.

For a 2D array of shape (2, 3) with int32 elements (4 bytes per element), the stride for each dimension is as follows:

Stride for the rows (first dimension): 12 bytes (3 elements × 4 bytes)

Stride for the columns (second dimension): 4 bytes (1 element × 4 bytes)

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

print(arr_2d.strides)

(12, 4)

19. Write a NumPy program that creates a 1D array of 20 elements and use reshape() to create a (4, 5) matrix. Slice a (2, 3) sub-matrix and print its strides.

In [11]:
import numpy as np
from numpy import random

num1=np.arange(20)
print(num1)
num1=num1[:,np.newaxis]
num2=num1.reshape(4,5)
print(num2)
num3=num2[:2,:3]
print("\nSliced (2, 3) sub-matrix:\n", num3)
print(num3)
print(num3.strides)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

Sliced (2, 3) sub-matrix:
 [[0 1 2]
 [5 6 7]]
[[0 1 2]
 [5 6 7]]
(40, 8)
