9. Write a NumPy program to sort an given array by the nth column.

Original array:

[[1 5 0]

[3 2 5]

[8 7 6]]

Sort the said array by the nth column:

[[3 2 5]
[1 5 0]
[8 7 6]]

In [10]:
import numpy as np
from numpy import random

num=random.randint(0,10,size=(3,3))
print(num)
n=int(input("enter the number of column by which you wanna to sort the Array:    "))
num=num[num[:,n].argsort()]
print(num)

[[3 0 9]
 [7 2 9]
 [8 0 0]]
[[8 0 0]
 [3 0 9]
 [7 2 9]]


20. Write a NumPy program that creates a 2D NumPy array and uses a mask array (boolean array) for indexing to select a subset of 

elements that match the mask criteria.


In [16]:
num=random.randint(1,10,size=(2,2))
mask=num>5
print(f" the Array is:{num}")
num2=num[mask]
print("The selected Array Is::")
print(num2)



 the Array is:[[2 2]
 [1 8]]
The selected Array Is::
[8]
