10. Write a NumPy program to compute pearson product-moment correlation coefficients of two given arrays.

Sample Output:

Original array1:
[0 1 3]

Original array1:
[2 4 5]

Pearson product-moment correlation coefficients of the said arrays:
[[1. 0.92857143]
[0.92857143 1. ]]

In [1]:
import numpy as np

x = np.array([0, 1, 3])

y = np.array([2, 4, 5])

print("\nOriginal array1:")
print(x)

print("\nOriginal array1:")
print(y)

print("\nPearson product-moment correlation coefficients of the said arrays:\n", np.corrcoef(x, y))



Original array1:
[0 1 3]

Original array1:
[2 4 5]

Pearson product-moment correlation coefficients of the said arrays:
 [[1.         0.92857143]
 [0.92857143 1.        ]]


13. Write a Python program to count number of occurrences of each value in a given array of non-negative integers.
Note: bincount() function count number of occurrences of each value in an array of non-negative integers in the range of the array between the minimum and maximum values including the values that did not occur.

Sample Output:

Original array:
[0, 1, 6, 1, 4, 1, 2, 2, 7]

Number of occurrences of each value in array:
[1 3 2 0 1 0 1 1]

In [2]:
import numpy as np

array1 = [0, 1, 6, 1, 4, 1, 2, 2, 7] 

print("Original array:")
print(array1)

print("Number of occurrences of each value in array: ")
print(np.bincount(array1)) 

Original array:
[0, 1, 6, 1, 4, 1, 2, 2, 7]
Number of occurrences of each value in array: 
[1 3 2 0 1 0 1 1]
