5. Write a NumPy program to get the indices of the sorted elements of a given array.

Expected Output:

Original array:
[1023 5202 6230 1671 1682 5241 4532]

Indices of the sorted elements of a given array:
[0 3 4 6 1 5 2]

In [1]:
import numpy as np

# Creating a NumPy array for student IDs
student_id = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])

In [2]:
i=np.argsort(student_id)
print(i)

[0 3 4 6 1 5 2]



20. Write a NumPy program that creates a 2D NumPy array and uses a mask array (boolean array) for indexing to select a subset of elements that match the mask criteria.


In [3]:
import numpy as np

array_2d = np.random.randint(0, 100, size=(5, 5))

mask = array_2d > 50

selected_elements = array_2d[mask]

print('Original 2D array:\n', array_2d)
print('Mask array (elements > 50):\n', mask)
print('Selected elements using the mask:\n', selected_elements)

Original 2D array:
 [[52 49 22 81 68]
 [62 44 12 98  3]
 [98 35 36 11 72]
 [13 75 78 84 61]
 [40 80 79 54 83]]
Mask array (elements > 50):
 [[ True False False  True  True]
 [ True False False  True False]
 [ True False False False  True]
 [False  True  True  True  True]
 [False  True  True  True  True]]
Selected elements using the mask:
 [52 81 68 62 98 98 72 75 78 84 61 80 79 54 83]
